name: Minecraft Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: '17'

    - name: Download Minecraft Server
      run: wget https://launcher.mojang.com/v1/objects/64663c3957e1f70d88f7cb1a44173632f032ac3f/server.jar -O minecraft_server.jar

    - name: Accept EULA
      run: echo "eula=true" > eula.txt

    - name: Start Minecraft Server
      run: java -Xmx1024M -Xms1024M -jar minecraft_server.jar nogui
